#!/usr/bin/env python3
from Bio.Blast.Applications import NcbiblastxCommandline
#from Bio.Blast import NCBIWWW
from Bio.Emboss.Applications import NeedleCommandline
from Bio import AlignIO


#BLAST search
blastx_cline = NcbiblastxCommandline()
query = "opuntia.fasta"
db = "nr"
evalue = 0.001
outfmt = 5
out= "bat.xml"


#over the internet, but not at this moment
fasta_sequence = open("Bat18-762.fasta").read()
result_blast = NCBIWWW.qblast("blastn", "nt", fasta_sequence)

#result saved as xml file
with open("result_blast.xml", "w") as out_handle:
out_handle.write(result_blast.read())
result_blast.close()


#alignment of the BLAST match

#using EMBOSS
needle_cline = NeedleCommandline()
needle_cline.asequence= "Bat18-762.fasta"
needle_cline.bsequence= "beta.fasta"
needle_cline.gapopen= 10
needle_cline.gapextend= 0.5
needle_cline.outfile= "first_alignment.txt"

#load the alignment as emboss to identify the important trait
alignment = AlignIO.read("first_alignment.txt", "emboss")
print(alignment)

#as a matter of speed try in another time invoking pairwise2
